# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

warnings_are_errors: false
language: r
r:
  - oldrel
  - release
  - devel
r_packages:
  - devtools
  - roxygen2
  - testthat
  - gt
  - kableExtra
  - tidyverse
r_github_packages:
  - r-lib/vdiffr
after_success:
  - Rscript -e 'covr::codecov()'
